### ISSUE TITLE
today() fails if today contains todo with start_date == None

### ISSUE THREAD

**Issue by bkleinen** [thingsapi/things.py#119]
**To Reproduce**

see title.

  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/things/api.py", line 526, in today
    result.sort(key=lambda task: (task["today_index"], task["start_date"]))
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Expected behavior**

not failing :)

will provide pr for fix.

**Comment by mikez** [comment]
@bkleinen See #120 (/cc @AlexanderWillner)
