### ISSUE TITLE
implement api.trashed

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#16]
**Goal**
- As a things-cli user
- I want to look at the trash
- so that I know what was deleted

**Suggested approach**
In order to achieve this goal I suggest to implement `api.trashed`

**Additional context**
testing via https://github.com/thingsapi/things-cli

// @mikez

**Comment by mikez** [comment]
Some suggestions:

1. Call the API `things.trash` to keep naming consistent with the Things app.
2. Make it a wrapper around `things.tasks()` and add a new `bool`-parameter called `trashed` to said function.
