### ISSUE TITLE
api.today does not return new to-todos

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#19]
**To Reproduce**
1. Schedule a to-do called `A` for next day
2. Wait until 00:00
3. Call `api.today`

**Expected behavior**
The to-do called `A` should be returned.

**Comment by mikez** [comment]
See comment in `things.today`'s documentation. :)

**Comment by AlexanderWillner** [comment]
I see. At the same time I disagree ;) Imho to-do items shown in `Today` (regardless whether marked yellow or not) should be returned. This is how I did it in the past: https://github.com/AlexanderWillner/KanbanView/blob/df79c111978f4e3048f0674c4554e2f483120ffe/things3/things3.py#L217

**Comment by mikez** [comment]
@AlexanderWillner There seem to be more cases though when you're looking into the future. For example:
- tasks with due-dates that are in Inbox, Anytime, or Sometime.
- recurring tasks that haven't been scheduled yet
- others

This requires a careful analysis of the Things app behavior.

**Comment by AlexanderWillner** [comment]
Right, this might get complicated. Let me check tomorrow: I think `then run the Things app to update the database` is not correct, the user has to click on the yellow button to remove the color and only then it will get returned from the API (I think).

**Comment by mikez** [comment]
@AlexanderWillner Good catch. Confirmed by testing. Updated docs.
