### ISSUE TITLE
implement api.search

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#22]
**Goal**
- As a things-cli user
- I want search for tasks
- so that I find what I'm looking for

**Suggested approach**
In order to achieve this goal I suggest to implement `api.search`

**Additional context**
Will extend https://github.com/thingsapi/things-cli afterwards.

**Comment by mikez** [comment]
@AlexanderWillner I encourage you to try implementing it. That will be a good opportunity to learn the new code. Also, don't assign me to stuff, I don't like that. :-)

**Comment by AlexanderWillner** [comment]
2x 👍

**Comment by AlexanderWillner** [comment]
@mikez maybe you could review https://github.com/thingsapi/things.py/pull/27
