### ISSUE TITLE
ERROR: pip3 install things.py

### ISSUE THREAD

**Issue by mikez** [thingsapi/things.py#24]
**To Reproduce**
1. Run  `pip3 install things.py`
2. See error
```
ERROR: Could not find a version that satisfies the requirement things.py
ERROR: No matching distribution found for things.py
```

**Expected behavior**
things.py is installed.

**Comment by AlexanderWillner** [comment]
Do you have a PiPy account? Just tested the upload: https://test.pypi.org/project/things/

**Comment by mikez** [comment]
https://pypi.org/user/mikez/

**Comment by AlexanderWillner** [comment]
Can't use the name `things` : https://pypi.org/project/Things/ - I suggest to use https://pypi.org/project/things-api/

**Comment by mikez** [comment]
@AlexanderWillner Why not use `things.py` as in the README?

**Comment by AlexanderWillner** [comment]
You've a point 👍

**Comment by AlexanderWillner** [comment]
> https://pypi.org/user/mikez/

Funny: I used https://pypi.org/project/emlx/ a lot in another project of mine :)
