### ISSUE TITLE
Interoperability with built-in Things API

### ISSUE THREAD

**Issue by mikez** [thingsapi/things.py#29]
**Goal**
I just discovered that the Things.app has a built-in API interface. See [here](https://culturedcode.com/things/support/articles/2803573/). One might consider making our names consistent to this API. Also, maybe we can make good use of it as well.

**Suggested approach**
Look more into the provided Things API and how it can improve this library.

**Comment by mikez** [comment]
I found a library on PyPI implementing aspects of this. Source [here](https://gist.github.com/6dd6220601b2d3173f44317939ff846f).

**Comment by mikez** [comment]
Some findings after research:

Their JSON keys are very close to ours. Made two changes involving "deadline" and "checklist-item" on our end. Other then that, I find the remaining differences confusing and adding more complexity.

- Some fields are merged together, for example, start and start_date is merged to "when".
- stop_date is called "completion-date", which is confusing, because a task can also be canceled.
- "attributes" and splitting "status" into various properties I find unhelpful too.

The API can be combined with the xcall app for x-callback-urls. However, as of now it mostly seems useful for changing the Things app, not so much for getting data from it.

**Comment by AlexanderWillner** [comment]
> The API can be combined with the [xcall app](https://github.com/martinfinke/xcall/) for x-callback-urls. However, as of now it mostly seems useful for changing the Things app, not so much for getting data from it.

Also the ways on how to modify items are rather limited.

**Comment by mikez** [comment]
Research closed.
