### ISSUE TITLE
Consider publishing the API documentation via GitHub Pages

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#35]
**Goal**
- As a user of this library
- I want to easily look at the documentation
- so that I'm confident it does what I need

**Suggested approach**
In order to achieve this goal I suggest to run `pdoc` via GitHub Actions and publish the results via GitHub Pages.

**Additional context**
We do already have `make doc`

**Comment by mikez** [comment]
👌  I like how clean it is.

Two notes:
1. You may want to generate documentation for the root `things` and not `things.api`. The latter may have internal methods.
2. Check pandas and numpy documentation generation; they have similar docstrings and I'm guessing there are parsing methods one can reuse.

**Comment by mikez** [comment]
https://numpydoc.readthedocs.io/en/latest/format.html
https://github.com/numpy/numpydoc

Note: I much prefer your clean layout to the navigational structure NumPy and pandas have. However, when it comes to the parsing of docstrings, they might have helper methods one can use, to turn it into HTML or markdown.

**Comment by AlexanderWillner** [comment]
See https://thingsapi.github.io/things.py :
 - [x] it's using the numpy docstring formatter
 - [x] it's pointing to the high level view
 - [x] it's hosted by GitHub pages (via the `docs` folder)
 - [x] it can be updated via `make doc`
 - [ ] it does not yet update itself automatically via GitHub actions

**Comment by mikez** [comment]
Wonderful. This already looks good! Some minor tweaking might be needed here and there.

## Examples

1. Two different renderings of similar lists.

![image](https://user-images.githubusercontent.com/216956/113409700-250cf500-93b2-11eb-9104-697a0acbb282.png)

2. Like you mentioned, cross references of the type `things.tasks` and `things.Database` don't work. Maybe one needs a function to resolve these, so they link to the right place? — Or one could also change the documentation itself, but then complexity and legibility might go up.

![image](https://user-images.githubusercontent.com/216956/113410048-cd22be00-93b2-11eb-8afd-f6c278a9dc65.png)
