### ISSUE TITLE
Return project/area name and project_uuid/area_uuid

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#42]
**Goal**
- As a KanbanView developer
- I want to receive both project/area and their uuid
- so that I can reuse most of the old code when using things.py

**Suggested approach**
In order to achieve this goal I suggest to return `"project": "test project", "project_uuid": "Uaxh5ytCho8CSTNsUCxtAv"` instead of `"project": "Uaxh5ytCho8CSTNsUCxtAv"`

**Additional context**

**Comment by mikez** [comment]
@AlexanderWillner Another approach might be to return
```json
{
    ...
    "project": {"uuid": "...", title: "..."}
    ...
}
```

Settings `include_items` to `true` would also give you that... and more.

Yet another approach is to use `things.projects()` and `things.areas()` to create a `dict` that maps ids to names. You can use that dict for every request. That way you can easily lookup any area/project ID if needed.

**Comment by AlexanderWillner** [comment]
Returning such a dict be a cleaner approach. Always enabling `include_items` or always run a second query seems to be a bit too much (I think getting the context of a to-do in terms of a title is often needed anyways).

**Comment by mikez** [comment]
@AlexanderWillner To clarify, you wouldn't always run that second query (things.projects(), things.areas()). Rather, it's something you do **once** and then store in memory as a Python dict for all subsequent requests.
