### ISSUE TITLE
Consider to adapt aspects of "Hypermodern Python"

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#45]
**Goal**
- As a a developer
- I want to work with a good project structure
- so that extending the library is fun

**Suggested approach**
In order to achieve this goal I suggest to adapt some concepts from [Hypermodern Python](https://cjolowicz.github.io/posts/hypermodern-python-01-setup/) (or other resources) where reasonable.

**Additional context**
n/a

**Comment by mikez** [comment]
What gives you the confidence that these are "good" suggestions for this project?
IMO these suggestions add more bulk, dependencies, and overhead than needed.

**Comment by AlexanderWillner** [comment]
1. It's a long list of (probably) best practices and we could consider adopting some parts of it where it makes sense, not all.
2. We're already using some parts (e.g. we're using `black`, several linters, `coverage`, ...)
3. I like to learn from the experience of others ;)

**Comment by mikez** [comment]
@AlexanderWillner I'm a big fan of learning from the experience of others. :-)

However, in my opinion, the concept of "best practices" in (Python) software engineering is a misnomer. It's a very young field with lots of changing philosophies, opinions, and environments. The choices will depend strongly on the context. This is unlike more traditional engineering, which has been around for way longer and as I understand has several best practices.

P.S. I don't see "black" mentioned anywhere in that article.

**Comment by mikez** [comment]
@AlexanderWillner I just realized this is a 6-piece article. Thanks for sharing! :)
