### ISSUE TITLE
Monkey patch `# pragma: no cover`

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#67]
See https://github.com/thingsapi/things.py/pull/65#discussion_r615410089

**Comment by mikez** [comment]
@AlexanderWillner This is obsolete right? I think we removed that code.

**Comment by AlexanderWillner** [comment]
We've other instances like the following, don't we?

https://github.com/thingsapi/things.py/blob/230fcd9ddcdf3737114fcd38676bccd9995c8951/things/api.py#L705

**Comment by mikez** [comment]
👌 You might fix it like this:
https://stackoverflow.com/a/46239371
