### ISSUE TITLE
Implement getting `recurring` / `repeating` items

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#73]
**Goal**
- As a user
- I want to get my scheduled items sorted by due date
- so that I can see what's recurring

**Suggested approach**
In order to achieve this goal I suggest to either implement `things.recurring` or probably even better `things.upcoming(recurring=True)`

**Additional context**
n/a

**Comment by mikez** [comment]
I believe the Things term here is "Repeating".
If you search for "Repeating" with ⌘F they show up.

One clarification about Upcoming: are instances of repeats only created on the day of the event itself? How and when does the database create instances?

**Comment by AlexanderWillner** [comment]
The [query from my old script](https://github.com/AlexanderWillner/things.sh/blob/master/plugins/repeating.sh) simply filters by `recurrenceRule` and I assume the procedure for creating instances is quite similar to the items that pop up in the Today list when a scheduled event pops up.

**Comment by mikez** [comment]
Ah, I see. So then the instance is first created when you click "OK".

**Comment by mikez** [comment]
How about we use Pareto principle for now?

1. Important issues: keep it open.
2. Less important issue: close and add "opportunity" tag.

**Comment by AlexanderWillner** [comment]
We can close all issues, however, this is usually not how I manage a backlog (e.g., getting recurring tasks is indeed not implemented). The issue section would then rather be a log file of discussions. But I'm fine with this.

**Comment by mikez** [comment]
Here's how I see it:

1. Open Issues (Inbox of new + most important)
2. Backlog of potential opportunities; less important ("future opportunities" label)

What do you think? What flow seems more convenient for you?

**Comment by AlexanderWillner** [comment]
I'm fine testing the `future opportunities` approach. Let's see and learn what works best.
