### ISSUE TITLE
Add an option to include "yellow" tasks

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#79]
**Goal**
- As a user
- I want to receive from the API the same list of tasks that I see in the application
- so that I don't have to click on the yellow "OK" button

**Suggested approach**
In order to achieve this goal I suggest to have, at least as a starting point, an experimental flag set for the `today` method to also include yellow tasks.

**Additional context**
We've `database.was_modified_today` and a warning for this issue, as it's not completely trivial to implement (a couple of edge cases). However, at least for the today overview it would be nice to have.

**Comment by AlexanderWillner** [comment]
@mikez my proposal is to enhance the `today` query by changing from

```sql
AND TASK.start = 1
AND TASK.startDate IS NOT NULL
```

to

```sql
AND (TASK.start = 1 OR TASK.start = 2)
AND TASK.startDate <= strftime('%s', 'now')
```

**Comment by mikez** [comment]
Sounds good to me as long as you document it.

Two remarks:
1. I suggest to organize `things.today` like this:
```python
regular_today_tasks = tasks(start_date=True, start="Anytime", ...)
# The database reflects the state of the Things app when it was last run.
# For more recent tasks the yellow "OK" button might need to be clicked
# before the database includes them. Here, we try to deduce what those
# tasks would be, so they show up in the result as well.
unconfirmed_today_tasks = ...

return merge(unconfirmed_today_tasks, regular_today_tasks)
```

2. I propose to clearly list all the edge cases in a comment in `things.today`. We don't need to implement all this time around (Pareto principle), but it will help for the future to improve our mental model in case we missed something.

**Comment by AlexanderWillner** [comment]
Wrt. documentation: as the implementation shows to-dos that pop-up in the `Today` list (i.e. tasks with a `start_date` <= `today`), I'm not sure whether there are actually edge cases that need to be documented.

**Comment by mikez** [comment]
@AlexanderWillner Things for the reminder. I hope to get around to this review soon.

To clarify with documentation: the most common pop-up I get are for repeating tasks. That would be one such case. There might be several others too, for example deadlines. I think it could be beneficial to think through what all the cases are.

**Comment by mikez** [comment]
@AlexanderWillner Does that make sense to you... or would you like me to clarify more?
