### ISSUE TITLE
Consider introducing constants instead of hard coded string

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#81]
**Goal**
- As a user of the API
- I want to use IDE completions
- so that I can avoid typos and now which values are valid

**Suggested approach**
In order to achieve this goal I suggest to use constants, ideally with some form of type hinting. E.g. via an `enum`.

**Additional context**
For example instead of `todos = things.todos(start="Anytime")` it would be `todos = things.todos(start=StartType.ANYTIME)`

```python
class StartType(str, Enum):
    """Valid values for to-do start."""

    INBOX: str = "Inbox"
    ANYTIME: str = "Anytime"
    SOMEDAY: str = "Someday"
```

**Comment by AlexanderWillner** [comment]
Actually, using the `@validate_arguments` decorator of [pydantic](https://github.com/samuelcolvin/pydantic) together with using some type hinting (e.g. using `Literal`) works quite nicely.

**Comment by mikez** [comment]
IDE completions are handy, I agree. I also think `Enum` and `@validate_arguments` are useful. However, in this instance, it seems like overengineering to me, because `start` is already being validated. I vote *not* to do this.

**Comment by mikez** [comment]
@AlexanderWillner I see it as a trade-off. For smaller non-stable projects I find type hinting adds more maintenance costs, more dependancies, and makes code less legible. I modeled the validation after pandas who does validation manually as well. — My intention here is to create a good user experience for the users of the API.

**Comment by mikez** [comment]
To clarify my bias: I spend a lot of time in non-IDE environments like IPython and the shell.

**Comment by mikez** [comment]
To clarify: my vote is **NO** and to close this. Reason: see above (overengineering).

**Comment by AlexanderWillner** [comment]
My vote is **YES**, as imho arbitrary constants should be defined instead of just remembered by the user / documented somewhere (e.g. see [PEP 8](https://www.python.org/dev/peps/pep-0008/#constants)). Let's see if a third party jumps in at a later stage to pull the needle to one or the other direction ;)

**Comment by mikez** [comment]
Replacing

```py
import things
things.todos(start="Anytime")
```

with

```py
import things
from things import StartType

things.todos(start=StartType.ANYTIME)
```

is overengineering to me.

If you want easier type completion, you could consider parsing the doc string in the IDE. See libraries like pandas and numpy which do it the way we do it.

**Comment by mikez** [comment]
References:

- [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) (look for compression parameter)
- https://docs.python.org/3/library/functions.html#open
- …

**Comment by AlexanderWillner** [comment]
Ok, ok, ok. I see we come from different backgrounds - as also shown in our discussion about static/automatic type checking ;) I was more thinking in the lines `things.todos(start=things.START_ANYTIME)`(which would be shorter and also allows for `things.todos(start="Anytime")` at the same time. But I see/accept that this is not too common in the `Python` world and I'm willing to follow the Python idiomatic language convention...you never stop learning.

**Comment by mikez** [comment]
@AlexanderWillner What's your background? I intent not to be dogmatic, but rather to think from first principles. I like whatever makes the library easy to use and the code easy to read for someone who is new to this project.

**Comment by AlexanderWillner** [comment]
Mainly statically typed languages, such as `Java`,  my favourite language in this context is `rust`.
