### ISSUE TITLE
Follow Semantic Versioning and use version 0.1.0 or even 1.0.0

### ISSUE THREAD

**Issue by AlexanderWillner** [thingsapi/things.py#84]
**Goal**
- As a user
- I want the project to follow reasonable version numbers
- so that I better understand the versions that are used for the library

**Suggested approach**
In order to achieve this goal I suggest to follow [Semantic Versioning](https://semver.org). Maybe use 0.1.0 or even 1.0.0

**Additional context**
-

**Comment by mikez** [comment]
👌 I like MAJOR.MINOR.PATCH. I'd defer this discussion to when we're ready for 1.0.0 though.

For the 0.0.X versions, I'd prioritize ease of changing things and getting the initial design right and not worry to much about the versioning numbers. As of now, there hasn't been much feedback yet.

**Comment by mikez** [comment]
@AlexanderWillner How about we add a tag called "opportunity"? These are issues we can reopen later again if needed—they are optional feature opportunities to be considered later.

**Comment by AlexanderWillner** [comment]
I also explicitly created a milestone to attach this issue to - after realising where milestones are ;)
