### ISSUE TITLE
Clean up issues list

### ISSUE THREAD

**Issue by mikez** [thingsapi/things.py#85]
**Goal**
- As a things.py developer
- I want the open issues list to be free of constipation
- so that I have an overview of new and important open issues.

**Suggested approach**
In order to achieve this goal I suggest @AlexanderWillner to close all issues that aren't planned to be actively worked on. They can be reopened later if needed. Maybe they can be given the tag "#opportunity" too, which means "opportunity in the future but not actively worked on".

**Comment by AlexanderWillner** [comment]
Well, I closed a few and extensively introduced some tags...

**Comment by mikez** [comment]
👌
