### ISSUE TITLE
4 build-tests failing

### ISSUE THREAD

**Issue by mikez** [thingsapi/things.py#97]
I updated the `README.md` and noticed several Github build tests failing.

Were some dependent libraries updated such as `pylint`?

<small>Maybe a future solution could be to specify a specific version of dependent libraries in https://github.com/thingsapi/things.py/blob/main/.github/workflows/tests.yml?</small>

/cc @AlexanderWillner

**Comment by mikez** [comment]
@AlexanderWillner Possibly the changes made in #96 could help with this.

**Comment by AlexanderWillner** [comment]
Green again here : https://github.com/thingsapi/things.py/pull/104

**Comment by AlexanderWillner** [comment]
Basically fixed
