### ISSUE TITLE
Things Beta date format change

### ISSUE THREAD

**Issue by NickChristensen** [thingsapi/things.py#98]
Hey, just a heads up: In mid-March, the beta made several changes in the db. Several seem to just be renamed columns, but I've been banging my head on the encoding of `startDate` and thought I'd share what I found in case it's helpful when they roll this out to a release version. In Javascript:

```js
// task with a startDate of Apr 9, 2023 = 132596864
const parseStartDate = (startDate) => {
  const DAYS = 128;
  const MONTHS = 32 * DAYS;
  const YEARS = 16 * MONTHS;

  let year = Math.floor(startDate / YEARS);
  startDate -= year * YEARS;
  let month = Math.floor(startDate / MONTHS);
  startDate -= month * MONTHS;
  let day = Math.floor(startDate / DAYS);

  console.log(year, month, day);
  return new Date(year, month - 1, day);
};
```

Sorry for the issue, feel free to close it. Just wanted to pass this along, as I've used this codebase to understand several things about the Things database.

**Comment by hlipnick** [comment]
Thanks for pointing this out, @NickChristensen.  Definitely saved me some time in debugging a python script of mine after the Database change in the latest update.  Do you know what format the 'reminderTime' is stored in?  For a task with a reminder set at 5:38pm on 4/11/23, I get the timestamp value in the database of 1180696576.  Running that through your function doesn't give the expected output, and I'm not familiar enough with what date format they're using to understand what else it might be.  If you have moment to shed some light on it I'd really appreciate it.

**Comment by NickChristensen** [comment]
I don't have any insight there, sorry. I'd suggest creating several todos and looking at their `reminderTime` in the database to infer patterns. I started with 1 day apart, 10 days apart, etc, then eventually noticed a discrepancy across month and year thresholds. Sorry I couldn't be more help!

**Comment by hlipnick** [comment]
@NickChristensen - No worries.  Fortunately a little head scratching and a lot of being guided by your function made me realize that they're actually not storing a full date as the reminder time, but rather an offset from midnight of the startDate.  This is the function I came up with to convert (in Python, but essentially the exact same logic) which can then be added to the startDate:

```python
def convert_new_style_database_time(db_time, as_string = True, with_timezone_offset = True):
    """Convert from the new style database time introduced in April 2023 to a time object"""
    # FROM: https://github.com/thingsapi/things.py/issues/98
    # Convert timestamp to datetime
    if db_time is None:
        return None
    SECONDS = 8192
    MINUTES = 128 * SECONDS
    HOURS = 64 * MINUTES

    hour = math.floor(db_time / HOURS)
    db_time -= hour * HOURS
    minute = math.floor(db_time / MINUTES)
    db_time -= minute * MINUTES
    second = math.floor(db_time / SECONDS)
    # Retutnr a datetime object just with time
    time = datetime(1, 1, 1, hour, minute, second).time()
    return time
```

**Comment by NickChristensen** [comment]
Wow, good find!

**Comment by mikez** [comment]
@NickChristensen Thanks for sharing. I'm glad to hear the code was helpful on your learning journey. As for fixing the new `start_date` in the code, might you give me some more examples like "Apr 9, 2023 = 132596864" that you find in your database? I can't check here, since I don't have the new Things yet.

@hlipnick 🙂. Do you think it would make sense to include `reminder_time` in the `things.py` output?

>     time = datetime(1, 1, 1, hour, minute, second).time()

Note, if you don't want to travel back to year 1, you can also do 
```pycon
>>> import datetime
>>> datetime.time(hour, minute, second)
```

Also, if either of you could run

>>> import things
>>> things.Database().get_version()

the would help me know what version the change is at. (I'm at version 21 here.)

**Comment by NickChristensen** [comment]
You bet! I'm away from a computer for about a week, but if someone doesn't beat me to it I'd be happy to provide more test values.

**Comment by AlexanderWillner** [comment]
Thanks for the analysis. Have you figured out how to query the new `startDate` with SQL? E.g., see https://github.com/thingsapi/things.py/blob/main/things/database.py#L711

**Comment by mikez** [comment]
@NickChristensen Thanks to your post, I was able to implement a fix. Details in commit https://github.com/thingsapi/things.py/commit/e64bea80c0b7c065dcc51c25744dbf5a9b7fcb60.

If you run the development version of things.py with the `print_sql=True` flag, you can see what's going on:

```sql
SELECT date(
    CASE
        WHEN TASK.startDate
    THEN
        format(
            '%d-%02d-%02d',
            (TASK.startDate & 134152192) >> 16,
            (TASK.startDate & 61440) >> 12,
            (TASK.startDate & 3968) >> 7
        )
    ELSE
        TASK.startDate
    END
) AS start_date
FROM TMTask AS TASK
```

**Comment by chrisgurney** [comment]
Thank you all for the analysis, and thank you for sharing your solution @mikez! Super helpful, as I too was pulling my hair out!

FYI I was able to apply the same query change for `TMTask.deadline` dates as well, over in [my project](https://github.com/chrisgurney/things2md).

**Comment by AlexanderWillner** [comment]
> as I too was pulling my hair out!

might make sense to use our library then ;)

**Comment by mikez** [comment]
@chrisgurney Thanks for chiming in. I took a look at things2md!

If you'd enjoy to do so, how about refactoring things2md to use `things.py` for the SQL fetches? That way, we can all support each other when things break next time—as opposed to us all having individual code-bases.

For example, `query_subtasks` (in your code) is a bit like:

```py
def query_subtasks(task_ids):
    return [things.get(task_id)['checklist'] for task_id in task_ids]
```

Happy to guide and answer questions if you chose to join our little things.py community. :)

**Comment by chrisgurney** [comment]
@mikez Good suggestion, thanks. If time allows in my next major revision -- or if Things4 comes along and breaks everything --- I'll definitely look into it. :)
