### ISSUE TITLE
Upgrade to work with pandoc 3.x

### ISSUE THREAD

**Issue by metbril** [thingsapi/things.py#99]
The library requires pandoc 2.x, but the most recent version is 3.x

See also:
https://github.com/chrizel/things-to-org/issues/1

**Comment by mikez** [comment]
@metbril Thanks for the note. Can we easily upgrade to 3.x or are there some breaking changes?

**Comment by metbril** [comment]
Sorry. I wouldn't know. I temporarily downgraded to 2.x to use the downstream software and never tried with 3.x

**Comment by AlexanderWillner** [comment]
where do we require pandoc 2.x?

**Comment by metbril** [comment]
See https://github.com/chrizel/things-to-org/issues/1 for a use case

**Comment by metbril** [comment]
I've examined the code in detail and found that the downstream script uses pandoc to convert from markdown to org. This has nothing to do with your library, as you stated. Sorry for the inconvenience. The library is and remains very useful though.

**Comment by mikez** [comment]
@metbril 👍

For context: the [things-to-org](https://github.com/chrizel/things-to-org) script reads `task["notes"]` via things.py and then uses the [pandoc Python library](https://github.com/boisgera/pandoc) for further processing.

I'm glad you pointed out the things-to-org library, I added it to the "Used By" section of the README.
